import streamlit as st
import numpy as np
import pandas as pd
import joblib
import os
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path
from datetime import datetime, timedelta

# ─── Page Config ────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="PredictiveMaint AI",
    page_icon="⚙️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Custom CSS ─────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:wght@300;400;600&display=swap');

:root {
    --bg: #0d0f14;
    --surface: #161b24;
    --border: #1f2937;
    --accent: #00e5ff;
    --accent2: #ff6b35;
    --green: #00ff87;
    --red: #ff4757;
    --text: #e2e8f0;
    --muted: #64748b;
}

html, body, [class*="css"] {
    font-family: 'DM Sans', sans-serif;
    background-color: var(--bg) !important;
    color: var(--text);
}

.stApp { background-color: var(--bg); }

/* Sidebar */
[data-testid="stSidebar"] {
    background-color: var(--surface) !important;
    border-right: 1px solid var(--border);
}

/* Title area */
.hero-title {
    font-family: 'Space Mono', monospace;
    font-size: 2.2rem;
    font-weight: 700;
    color: var(--accent);
    letter-spacing: -1px;
    line-height: 1.1;
}
.hero-sub {
    color: var(--muted);
    font-size: 0.9rem;
    margin-top: 4px;
    font-family: 'Space Mono', monospace;
}

/* Status cards */
.status-card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 1.5rem;
    text-align: center;
}
.status-healthy {
    border-left: 4px solid var(--green);
}
.status-failure {
    border-left: 4px solid var(--red);
}
.status-label {
    font-family: 'Space Mono', monospace;
    font-size: 0.7rem;
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 2px;
}
.status-value {
    font-family: 'Space Mono', monospace;
    font-size: 1.6rem;
    font-weight: 700;
    margin-top: 6px;
}
.status-value.green { color: var(--green); }
.status-value.red   { color: var(--red); }
.status-value.cyan  { color: var(--accent); }
.status-value.orange{ color: var(--accent2); }

/* Input labels */
label, .stSlider label { color: var(--text) !important; }

/* Section headers */
.section-header {
    font-family: 'Space Mono', monospace;
    font-size: 0.75rem;
    color: var(--accent);
    text-transform: uppercase;
    letter-spacing: 3px;
    margin: 1.5rem 0 0.75rem 0;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--border);
}

/* Metric box */
.metric-box {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 1.2rem;
}

/* Upload area */
.upload-notice {
    background: rgba(0,229,255,0.05);
    border: 1px dashed var(--accent);
    border-radius: 10px;
    padding: 1.2rem;
    color: var(--muted);
    font-size: 0.85rem;
    font-family: 'Space Mono', monospace;
    text-align: center;
}

/* Gauge container */
.gauge-wrap {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 0.5rem;
}
</style>
""", unsafe_allow_html=True)


# ─── Model Loading ───────────────────────────────────────────────────────────
@st.cache_resource
def load_models():
    """Try to load pre-trained models from disk."""
    models = {}
    for key, fname in [
        ("classifier", "classifier_model.pkl"),
        ("regressor", "regressor_model.pkl"),
        ("encoder", "label_encoder.pkl"),
    ]:
        if Path(fname).exists():
            models[key] = joblib.load(fname)
    return models

models = load_models()
models_loaded = all(k in models for k in ["classifier", "regressor", "encoder"])


# ─── Sidebar ─────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown('<div class="hero-title">⚙️ PredictMaint</div>', unsafe_allow_html=True)
    st.markdown('<div class="hero-sub">Industrial AI · v1.0</div>', unsafe_allow_html=True)
    st.markdown("---")

    if not models_loaded:
        st.markdown("""
        <div class="upload-notice">
        ⚠️ No trained models found.<br><br>
        Place these files in the same directory as this app:<br><br>
        <code>classifier_model.pkl</code><br>
        <code>regressor_model.pkl</code><br>
        <code>label_encoder.pkl</code><br><br>
        (Generated by the notebook's last cell)
        </div>
        """, unsafe_allow_html=True)
        st.markdown("")

    st.markdown('<div class="section-header">Machine Type</div>', unsafe_allow_html=True)
    machine_type = st.selectbox(
        "Product Quality Grade",
        ["L — Low", "M — Medium", "H — High"],
        label_visibility="collapsed"
    )
    type_map = {"L — Low": (0, 1, 0), "M — Medium": (0, 0, 1), "H — High": (1, 0, 0)}
    type_H, type_L, type_M = type_map[machine_type]

    st.markdown('<div class="section-header">Sensor Readings</div>', unsafe_allow_html=True)

    air_temp = st.slider(
        "Air Temperature (K)", min_value=290.0, max_value=310.0, value=298.1, step=0.1,
        help="Ambient air temperature in Kelvin"
    )
    proc_temp = st.slider(
        "Process Temperature (K)", min_value=300.0, max_value=320.0, value=308.6, step=0.1,
        help="Process temperature in Kelvin"
    )
    rot_speed = st.slider(
        "Rotational Speed (RPM)", min_value=1168, max_value=2886, value=1551,
        help="Tool rotational speed"
    )
    torque = st.slider(
        "Torque (Nm)", min_value=3.8, max_value=76.6, value=42.8, step=0.1,
        help="Applied torque in Newton-metres"
    )
    tool_wear = st.slider(
        "Tool Wear (min)", min_value=0, max_value=253, value=180,
        help="Cumulative tool wear time in minutes"
    )

    st.markdown("")
    run_btn = st.button("🔍  Run Diagnostics", use_container_width=True, type="primary")


# ─── Main Content ─────────────────────────────────────────────────────────────
st.markdown('<div class="hero-title">Industrial Machine Diagnostics</div>', unsafe_allow_html=True)
st.markdown('<div class="hero-sub">Predictive Maintenance · Real-time Failure Classification & RUL Estimation</div>', unsafe_allow_html=True)
st.markdown("")

# Build input vector
sample = np.array([[type_H, type_L, type_M, air_temp, proc_temp, rot_speed, torque, tool_wear]])
feature_names = ['Type_H', 'Type_L', 'Type_M', 'Air_T (K)', 'Proc_T (K)', 'RPM', 'Torque (Nm)', 'Tool Wear (min)']

# ─── Live sensor panel ────────────────────────────────────────────────────────
st.markdown('<div class="section-header">Live Sensor Panel</div>', unsafe_allow_html=True)

col1, col2, col3, col4, col5 = st.columns(5)
sensor_data = [
    ("Air Temp", f"{air_temp} K", "cyan"),
    ("Proc Temp", f"{proc_temp} K", "cyan"),
    ("RPM", f"{rot_speed:,}", "cyan"),
    ("Torque", f"{torque} Nm", "orange"),
    ("Tool Wear", f"{tool_wear} min", "orange"),
]
for col, (label, val, color) in zip([col1, col2, col3, col4, col5], sensor_data):
    with col:
        st.markdown(f"""
        <div class="status-card">
            <div class="status-label">{label}</div>
            <div class="status-value {color}">{val}</div>
        </div>
        """, unsafe_allow_html=True)

# ─── Diagnostics Results ──────────────────────────────────────────────────────
st.markdown('<div class="section-header">Diagnostic Results</div>', unsafe_allow_html=True)

if not models_loaded:
    st.info("📦 Load your trained model files (`.pkl`) alongside this app to enable predictions. See the sidebar for instructions.")
else:
    # Always compute predictions so the dashboard is live
    clf = models["classifier"]
    reg = models["regressor"]
    le  = models["encoder"]

    pred_class_idx = clf.predict(sample)[0]
    pred_proba = clf.predict_proba(sample)[0]
    failure_name = le.inverse_transform([pred_class_idx])[0]

    is_failure = failure_name != "No_Failure"
    rul = reg.predict(sample)[0] if is_failure else None

    # ── Status row ──
    res_col1, res_col2, res_col3, res_col4 = st.columns(4)

    card_cls = "status-failure" if is_failure else "status-healthy"
    status_color = "red" if is_failure else "green"
    status_icon = "🔴" if is_failure else "🟢"
    display_name = failure_name.replace("_", " ")

    with res_col1:
        st.markdown(f"""
        <div class="status-card {card_cls}">
            <div class="status-label">Machine Status</div>
            <div class="status-value {status_color}">{status_icon} {display_name}</div>
        </div>
        """, unsafe_allow_html=True)

    with res_col2:
        rul_display = f"{rul:.1f} min" if rul is not None else "∞ Healthy"
        rul_color = "red" if rul is not None and rul < 50 else "orange" if rul is not None else "green"
        st.markdown(f"""
        <div class="status-card">
            <div class="status-label">Remaining Useful Life</div>
            <div class="status-value {rul_color}">{rul_display}</div>
        </div>
        """, unsafe_allow_html=True)

    with res_col3:
        # Estimated failure clock time
        if rul is not None:
            failure_time = datetime.now() + timedelta(minutes=float(rul))
            ftime_display = failure_time.strftime("%H:%M")
            fdate_display = failure_time.strftime("%d %b %Y")
            ftime_color = "red" if rul < 50 else "orange"
            ftime_label = f"<div style='font-size:0.75rem;color:var(--muted);margin-top:2px;'>{fdate_display}</div>"
        else:
            ftime_display = "—"
            ftime_color = "green"
            ftime_label = "<div style='font-size:0.75rem;color:var(--muted);margin-top:2px;'>No failure predicted</div>"

        st.markdown(f"""
        <div class="status-card status-{'failure' if is_failure else 'healthy'}">
            <div class="status-label">⏰ Est. Failure Time</div>
            <div class="status-value {ftime_color}">{ftime_display}</div>
            {ftime_label}
        </div>
        """, unsafe_allow_html=True)

    with res_col4:
        confidence = float(np.max(pred_proba)) * 100
        st.markdown(f"""
        <div class="status-card">
            <div class="status-label">Model Confidence</div>
            <div class="status-value cyan">{confidence:.1f}%</div>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("")

    # ── Charts row ──
    chart_col1, chart_col2 = st.columns([1, 1])

    with chart_col1:
        st.markdown("**Failure Class Probabilities**")
        class_labels = [l.replace("_", " ") for l in le.classes_]
        colors = ["#ff4757" if l != "No Failure" else "#00ff87" for l in class_labels]
        fig_bar = go.Figure(go.Bar(
            x=pred_proba * 100,
            y=class_labels,
            orientation='h',
            marker_color=colors,
            text=[f"{v*100:.1f}%" for v in pred_proba],
            textposition='outside',
        ))
        fig_bar.update_layout(
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)',
            font=dict(color='#e2e8f0', family='DM Sans'),
            margin=dict(l=10, r=60, t=10, b=10),
            xaxis=dict(title="Probability (%)", gridcolor='#1f2937', range=[0, 105]),
            yaxis=dict(gridcolor='#1f2937'),
            height=280,
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    with chart_col2:
        st.markdown("**Tool Wear Health Gauge**")
        wear_pct = (tool_wear / 253) * 100
        gauge_color = "#ff4757" if wear_pct > 80 else "#ff6b35" if wear_pct > 60 else "#00ff87"
        fig_gauge = go.Figure(go.Indicator(
            mode="gauge+number+delta",
            value=wear_pct,
            number=dict(suffix="%", font=dict(color=gauge_color, size=36)),
            delta=dict(reference=60, increasing=dict(color="#ff4757"), decreasing=dict(color="#00ff87")),
            gauge=dict(
                axis=dict(range=[0, 100], tickcolor="#64748b", tickfont=dict(color="#64748b")),
                bar=dict(color=gauge_color, thickness=0.25),
                bgcolor='rgba(0,0,0,0)',
                borderwidth=0,
                steps=[
                    dict(range=[0, 60], color="rgba(0,255,135,0.08)"),
                    dict(range=[60, 80], color="rgba(255,107,53,0.08)"),
                    dict(range=[80, 100], color="rgba(255,71,87,0.12)"),
                ],
                threshold=dict(line=dict(color="#00e5ff", width=2), thickness=0.75, value=80),
            ),
        ))
        fig_gauge.update_layout(
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)',
            font=dict(color='#e2e8f0', family='DM Sans'),
            margin=dict(l=20, r=20, t=20, b=20),
            height=280,
        )
        st.plotly_chart(fig_gauge, use_container_width=True)

    # ── Feature importance radar ──
    if hasattr(clf, 'feature_importances_'):
        st.markdown('<div class="section-header">Feature Importance</div>', unsafe_allow_html=True)
        importances = clf.feature_importances_
        fig_imp = go.Figure(go.Scatterpolar(
            r=importances,
            theta=feature_names,
            fill='toself',
            fillcolor='rgba(0,229,255,0.1)',
            line=dict(color='#00e5ff', width=2),
            marker=dict(color='#00e5ff', size=6),
        ))
        fig_imp.update_layout(
            polar=dict(
                bgcolor='rgba(0,0,0,0)',
                radialaxis=dict(visible=True, gridcolor='#1f2937', tickfont=dict(color='#64748b')),
                angularaxis=dict(gridcolor='#1f2937', tickfont=dict(color='#e2e8f0')),
            ),
            paper_bgcolor='rgba(0,0,0,0)',
            font=dict(color='#e2e8f0', family='DM Sans'),
            margin=dict(l=60, r=60, t=20, b=20),
            height=340,
            showlegend=False,
        )
        st.plotly_chart(fig_imp, use_container_width=True)

    # ── Raw input summary ──
    with st.expander("🔬 Raw Input Vector"):
        input_df = pd.DataFrame(sample, columns=feature_names)
        st.dataframe(input_df.style.format("{:.2f}"), use_container_width=True)

# ─── Footer ──────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown(
    '<span style="font-family:Space Mono,monospace;font-size:0.7rem;color:#64748b;">'
    'PredictMaint AI · XGBoost-powered · Built with Streamlit</span>',
    unsafe_allow_html=True
)
